@miPuerto = http://localhost:8080

{{miPuerto}}

###
GET {{miPuerto}}

###
POST {{miPuerto}}
Content-Type: application/json

{
    "first_name": "Luis",
    "last_name": "Garcia",
    "email": "luis@g.mail",
    "password": "123456",
    "phone_number": 123456789
}

###
POST http://localhost:8000/api/sessions/login
Content-Type: application/json

{
    "username": "miltonriver",
    "password": "12345"
}

###
GET http://localhost:8000/api/sessions/current
authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI6IkNhbWkgcGV0aXRmb3VyIiwidXNlcm5hbWUiOiJjYW1pMjAxNyIsImlkIjoiNjY0ZDc3NDIwYWY5NWIxMDQ3ZmZlMWNiIiwiaWF0IjoxNzE2MzU1MTU1LCJleHAiOjE3MTY0NDE1NTV9.MiwQr3PTeLHZwhUFBxG-5h4qEpCOoQkPzCEcvr04HpM

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "title": "producto 14",
    "price": 456,
    "code": "uiodusad45564",
    "stock": 14
}